### PR TITLE
Server, Movement & Collision modifications

### PR DESCRIPTION
**Pull request by Koupah**
Added client side interpolation so that we can reduce the amount of packets the server sends the client, and the server now sends 70% less "status" packets but feels smoother than ever.

Math is still done on the same 15ms interval, but I am looking to change that. Just need to account for the new interval when modifying the math otherwise player speed among other things will be affected.

### CODE REVIEW

**Comment by XtraCube** [comment]
kinda funny how i was working on something like this already, but looks like this is better that my stuff. i do have one idea that i gotta implement into this PR before I think its merge ready

**Comment by Koupah** [comment]
I believe I am done with this PR, unless you require other changes

**Review by XtraCube — CHANGES_REQUESTED** [review]
everything is fine except line 36 in index.js

**Comment by Koupah** [comment]
Done

**Review by XtraCube — APPROVED** [review]

**Pull request merged**
