### PR TITLE
Update readme to include image example

### PR DESCRIPTION
**Pull request by Captain8771**
also my first PR on GH :)

### CODE REVIEW

**Comment by Captain8771** [comment]
dont mind the 4 updates. i messed up a few times

**Comment by XtraCube** [comment]
the image provided isn't a good example, you should probably take a screenshot of the whole play area, not just the preview image

**Comment by Captain8771** [comment]
> the image provided isn't a good example, you should probably take a screenshot of the whole play area, not just the preview image

ok ill do that (sorry for late reply i was eating lunch)

**Comment by Captain8771** [comment]
@XtraCube how about now?

**Comment by XtraCube** [comment]
low res screenshot, and i said the play area, not the entire thing.

> "If you want something done right, do it yourself"
> -Napoleon Bonaparte

**Comment by Captain8771** [comment]
> low res screenshot, and i said the play area, not the entire thing.
> 
> > "If you want something done right, do it yourself"
> > -Napoleon Bonaparte

ah right im stupid lol

**Comment by Captain8771** [comment]
for the low res part blame lightshot

**Comment by XtraCube** [comment]
inactive

**Pull request closed without merging**
